// 직군 / 직무
export const JOB_PARTS = [
    { value: "기획, 전략", label: "기획, 전략" },
    { value: "마케팅, 홍보, 조사", label: "마케팅, 홍보, 조사" },
    { value: "회계, 세무, 재무", label: "회계, 세무, 재무" },
    { value: "인사, 노무, HRD", label: "인사, 노무, HRD" },
    { value: "총무, 법무, 사무", label: "총무, 법무, 사무" },
    { value: "IT 개발, 데이터", label: "IT 개발, 데이터" },
    { value: "디자인", label: "디자인" },
    { value: "영업, 판매, 무역", label: "영업, 판매, 무역" },
    { value: "고객상담, TM", label: "고객상담, TM" },
    { value: "구매, 자재, 물류", label: "구매, 자재, 물류" },
    { value: "상품기획, MD", label: "상품기획, MD" },
    { value: "운전, 운송, 배송", label: "운전, 운송, 배송" },
    { value: "서비스", label: "서비스" },
    { value: "생산", label: "생산" },
    { value: "건설, 건축", label: "건설, 건축" },
    { value: "의료", label: "의료" },
    { value: "연구, R&D", label: "연구, R&D" },
    { value: "교육", label: "교육" },
    { value: "미디어, 문화, 스포츠", label: "미디어, 문화, 스포츠" },
    { value: "금융, 보험", label: "금융, 보험" },
    { value: "공공, 복지", label: "공공, 복지" },
];
